/** Drawable nouns and simple actions. Kept concrete: abstract words make for
 *  frustrating turns because there is nothing to actually draw. */
export const WORDS_EN: readonly string[] = [
  'apple', 'anchor', 'airplane', 'astronaut', 'avocado', 'arrow', 'axe', 'alien',
  'bicycle', 'banana', 'balloon', 'butterfly', 'bridge', 'bucket', 'beard', 'bee',
  'campfire', 'cactus', 'candle', 'castle', 'camera', 'carrot', 'clock', 'cloud',
  'crown', 'cupcake', 'compass', 'crab', 'chess', 'chimney', 'cow', 'computer',
  'dragon', 'dolphin', 'donut', 'drum', 'dice', 'diamond', 'door', 'dinosaur',
  'elephant', 'envelope', 'eagle', 'eyeball', 'easel', 'engine',
  'fireworks', 'flamingo', 'fountain', 'football', 'fork', 'fox', 'frog', 'feather',
  'guitar', 'giraffe', 'glasses', 'ghost', 'globe', 'gift', 'garden', 'goat',
  'hammer', 'helicopter', 'hamburger', 'hourglass', 'honey', 'hedgehog', 'harp',
  'igloo', 'island', 'ice cream', 'iron', 'insect',
  'jellyfish', 'jacket', 'jar', 'jungle', 'juggler',
  'kangaroo', 'kite', 'key', 'keyboard', 'koala', 'kettle',
  'lighthouse', 'ladder', 'lemon', 'lion', 'lamp', 'leaf', 'lizard', 'lollipop',
  'mountain', 'mushroom', 'mermaid', 'magnet', 'mailbox', 'monkey', 'moon', 'mask',
  'necklace', 'nest', 'needle', 'newspaper', 'nurse', 'noodles',
  'octopus', 'owl', 'orange', 'onion', 'oven', 'ostrich',
  'penguin', 'pizza', 'pirate', 'pyramid', 'parachute', 'pencil', 'piano', 'pumpkin',
  'queen', 'quilt', 'question mark',
  'rainbow', 'rocket', 'robot', 'rabbit', 'river', 'ring', 'raincoat', 'rose',
  'snowman', 'sandwich', 'submarine', 'skateboard', 'scissors', 'spider', 'sunflower',
  'staircase', 'starfish', 'shark', 'snail', 'sword', 'strawberry',
  'telescope', 'tractor', 'turtle', 'tornado', 'treasure', 'tent', 'toaster', 'tiger',
  'umbrella', 'unicorn', 'ufo',
  'volcano', 'violin', 'vampire', 'vase',
  'windmill', 'waterfall', 'whale', 'wallet', 'wizard', 'watch', 'wheel', 'window',
  'xylophone',
  'yacht', 'yarn', 'yo-yo',
  'zebra', 'zipper', 'zombie',
];
