/** Drawable nouns and simple actions. Kept concrete: abstract words make for
 *  frustrating turns because there is nothing to actually draw. */
export const WORDS_EN: readonly string[] = [
  'apple', 'anchor', 'airplane', 'astronaut', 'avocado', 'arrow', 'axe', 'alien',
  'bicycle', 'banana', 'balloon', 'butterfly', 'bridge', 'bucket', 'beard', 'bee',
  'campfire', 'cactus', 'candle', 'castle', 'camera', 'carrot', 'clock', 'cloud',
  'crown', 'cupcake', 'compass', 'crab', 'chess', 'chimney', 'cow', 'computer',
  'dragon', 'dolphin', 'donut', 'drum', 'dice', 'diamond', 'door', 'dinosaur',
  'elephant', 'envelope', 'eagle', 'eyeball', 'easel', 'engine',
  'fireworks', 'flamingo', 'fountain', 'football', 'fork', 'fox', 'frog', 'feather',
  'guitar', 'giraffe', 'glasses', 'ghost', 'globe', 'gift', 'garden', 'goat',
  'hammer', 'helicopter', 'hamburger', 'hourglass', 'honey', 'hedgehog', 'harp',
  'igloo', 'island', 'ice cream', 'iron', 'insect',
  'jellyfish', 'jacket', 'jar', 'jungle', 'juggler',
  'kangaroo', 'kite', 'key', 'keyboard', 'koala', 'kettle',
  'lighthouse', 'ladder', 'lemon', 'lion', 'lamp', 'leaf', 'lizard', 'lollipop',
  'mountain', 'mushroom', 'mermaid', 'magnet', 'mailbox', 'monkey', 'moon', 'mask',
  'necklace', 'nest', 'needle', 'newspaper', 'nurse', 'noodles',
  'octopus', 'owl', 'orange', 'onion', 'oven', 'ostrich',
  'penguin', 'pizza', 'pirate', 'pyramid', 'parachute', 'pencil', 'piano', 'pumpkin',
  'queen', 'quilt', 'question mark',
  'rainbow', 'rocket', 'robot', 'rabbit', 'river', 'ring', 'raincoat', 'rose',
  'snowman', 'sandwich', 'submarine', 'skateboard', 'scissors', 'spider', 'sunflower',
  'staircase', 'starfish', 'shark', 'snail', 'sword', 'strawberry',
  'telescope', 'tractor', 'turtle', 'tornado', 'treasure', 'tent', 'toaster', 'tiger',
  'umbrella', 'unicorn', 'ufo',
  'volcano', 'violin', 'vampire', 'vase',
  'windmill', 'waterfall', 'whale', 'wallet', 'wizard', 'watch', 'wheel', 'window',
  'xylophone',
  'yacht', 'yarn', 'yo-yo',
  'zebra', 'zipper', 'zombie',
  // Harder: still drawable, but they take a scene, a detail or some acting out
  // rather than one obvious shape.
  'accordion', 'aquarium', 'avalanche', 'bagpipes', 'black hole', 'blindfold',
  'bulldozer', 'catapult', 'chameleon', 'chandelier', 'constellation', 'dentist',
  'earthquake', 'eclipse', 'escalator', 'ferris wheel', 'fire hydrant', 'gondola',
  'hammock', 'hiccup', 'hopscotch', 'jack-in-the-box', 'lawn mower', 'lumberjack',
  'magician', 'microscope', 'mirage', 'mummy', 'narwhal', 'origami', 'periscope',
  'platypus', 'porcupine', 'quicksand', 'reflection', 'roller coaster', 'sandcastle',
  'saxophone', 'scarecrow', 'shipwreck', 'skeleton', 'sleepwalking', 'snow globe',
  'sphinx', 'stethoscope', 'sunburn', 'time machine', 'totem pole', 'traffic jam',
  'trampoline', 'tug of war', 'tuxedo', 'vacuum cleaner', 'ventriloquist',
  'wheelbarrow', 'wrecking ball',
];
