/**
 * The built-in board words. Mostly nouns with more than one meaning, which is
 * what makes a clue interesting: BANK, SPRING and PITCH can each be reached
 * from two or three directions.
 */
export const SPY_WORDS: readonly string[] = `
ACE AGENT AIR ALIEN ALPS AMAZON AMBULANCE ANCHOR ANGEL ANT APPLE ARM ARMY ARROW ATLAS
BABY BACK BALL BAND BANK BAR BARK BAT BATTERY BEACH BEAR BEAT BED BEE BELL BELT BERRY
BILL BLOCK BOARD BOLT BOMB BOND BOOM BOOT BOTTLE BOW BOX BRIDGE BRUSH BUCK BUFFALO BUG
BUTTON CABLE CAKE CALF CAMP CANAL CANDLE CAP CAPITAL CAR CARD CARROT CASINO CAST CASTLE
CAT CELL CENTER CHAIR CHANGE CHARGE CHECK CHEST CHICK CHIP CHOCOLATE CHURCH CIRCLE CLIFF
CLOAK CLOCK CLOUD CLUB CODE COLD COMET COMIC COMPOUND CONCERT CONDUCTOR CONTRACT COOK
COPPER COTTON COURT COVER CRANE CRASH CRICKET CROSS CROWN CRYSTAL CUP CYCLE DANCE DATE
DAY DECK DEGREE DESK DIAMOND DICE DINOSAUR DISEASE DOCTOR DOG DRAFT DRAGON DRESS DRILL
DROP DRUM DUCK DWARF EAGLE ENGINE EYE FACE FAIR FALL FAN FENCE FIELD FIGHTER FIGURE FILE
FILM FIRE FISH FLAG FLAT FLUTE FLY FOOT FORCE FOREST FORK FORTUNE FRAME FROG GAME GAS
GENIUS GHOST GIANT GLASS GLOVE GOLD GRACE GRASS GREEN GROUND GUM HAM HAND HAWK HEAD
HEART HELICOPTER HOLE HOOD HOOK HORN HORSE HOSPITAL HOTEL ICE ICE CREAM IRON ISLAND
IVORY JACK JAM JET JEWEL JUNGLE KEY KID KING KITE KIWI KNIFE KNIGHT LAB LAP LASER LAWYER
LEAD LEMON LETTER LIFE LIGHT LIMOUSINE LINE LINK LION LOCK LOG MAGIC MAIL MAMMOTH MAPLE
MARBLE MARCH MASS MATCH MERCURY MICROSCOPE MILL MINE MINT MISSILE MODEL MOLE MOON MOUNT
MOUSE MOUTH MUG NAIL NEEDLE NET NIGHT NINJA NOTE NOVEL NURSE NUT OCTOPUS OIL OLIVE OPERA
ORANGE ORGAN PALM PAN PANTS PAPER PARACHUTE PARK PART PASS PASTE PENGUIN PHOENIX PIANO
PIE PILOT PIN PIPE PIRATE PISTOL PIT PITCH PLANE PLASTIC PLATE PLATYPUS PLAY PLOT POINT
POISON POLE POOL PORT POST POUND PRESS PRINCESS PUMPKIN PUPIL PYRAMID QUEEN RABBIT RACKET
RAY REVOLUTION RING ROBIN ROBOT ROCK ROME ROOT ROSE ROULETTE ROUND ROW RULER SATELLITE
SATURN SCALE SCHOOL SCIENTIST SCORPION SCREEN SCUBA DIVER SEAL SERVER SHADOW SHARK SHIP
SHOE SHOP SHOT SINK SKYSCRAPER SLIP SLUG SMUGGLER SNOW SNOWMAN SOCK SOLDIER SOUL SOUND
SPACE SPELL SPIDER SPIKE SPINE SPOT SPRING SPY SQUARE STADIUM STAFF STAR STATE STICK
STOCK STRAW STREAM STRIKE STRING SUB SUIT SUPERHERO SWING SWITCH TABLE TABLET TAG TAIL TAP
TEACHER TELESCOPE TEMPLE THIEF THUMB TICK TIE TIME TOOTH TORCH TOWER TRACK TRAIN TRIANGLE
TRIP TRUNK TUBE TURKEY UNDERTAKER UNICORN VACUUM VAN VET VOLCANO WAKE WALL WAR WASHER WATCH
WATER WAVE WEB WELL WHALE WHIP WIND WITCH WORM YARD
BAKERY BANANA BLIZZARD BONE BUBBLE CACTUS CAMERA CANYON CARPET CHAIN CHEF CHIMNEY COCONUT
COMPASS CORN CROWD CURTAIN DETECTIVE DOLPHIN DOOR ECLIPSE EGG ELEPHANT FEATHER FLOOD
GARDEN GLACIER HAMMER HONEY IGLOO JELLY KANGAROO LADDER LANTERN LEAF MAGNET MASK MIRROR
MUSEUM NEST OCEAN ORBIT OWL PAINT PEARL PEPPER PILLOW PIZZA PLANET POCKET POTATO PUZZLE
RAINBOW RIVER ROCKET SAND SCARF SHELL SKELETON SOAP SPOON STORM SUGAR SWORD TENT THRONE
TIGER TOAST TORNADO TREASURE UMBRELLA VIOLIN WALLET WINDOW WIZARD ZEBRA
`
  // Two-word entries are written with a space and kept together.
  .replace(/ICE CREAM/g, 'ICE_CREAM')
  .replace(/SCUBA DIVER/g, 'SCUBA_DIVER')
  .split(/\s+/)
  .filter(Boolean)
  .map((w) => w.replace(/_/g, ' '));
